---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: monitoring-grafana
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCN90jcqzlRjAeNmcFUQCTW93gpmMlNJGLBN+ZMcqh/xdmeXyGkwOaioi3eQ9fbLLPgG1GG8Pt2eXirmG/PJEn5zOl4bWcpcdrgyhn3Eepvv1P95tpLXF91/6S8zto3Ffmpg8/vgOVOOT/gK2zdNO4KBV7gwqf63BES1QLi9RjrcfGOIlNDvDMI39LP/4nl9q9Wh8ozQG387bEYbKFaz2yU4E84KF1S5W2g9NVBxFRgTcXzK0DGW7WpkGcLOWAJ+q5WBOLo6TFt+Qt5A7Ls4phmJneuLztEFHJP81RBNhN2dO2qihzvHz+qTfWRbWQwvI8ZC1sxTz+iMIeq4mg+I2l+wBDFXA3duAKcBSeY/kSJK3qiip79HT/jf7hyf9e11LwrGKNBIH6KYR1QZm0NtW1YJcMop3v74xxdbunQ75wZlZXOQ/alecwK7TygcTIsZXeURl91LIHtplZrTAs3MBMmXE4jWk/Q783ypzKYAK7dtqF8eNHm3hZo4EAxkkr5qxdlyG7ZaM20bvmK6xyEHKsKFQ96seJOB7rXTFTIgvVQlJDh6Unf+ApJywSKsmeCtKlJXSsvRLNtKnf34llrU4yy5ezxHcNlYxoEzgDbkFbOMs5nLQApJmthxBKF7jkrii2RjSoHxd5lQnvTZ8S7cSsNAIuKT37mMQLjPiF78lM+OPdbqm5Ro+KNWaXp4ZJpXGXqyel4inm2BRnZ
    admin-user: AgAjcqDpPgGuG66j9msWu6gKRGICuSJ6x4gGvta0ZtAkrjv7jzaaHWVKi8dzLEX0GIoyx7AEknht/xyRAyfCoALF9RmE5q3sGQRhuDmMcq+3NEqr8J1RXKds4sdV6hLsAueNLRNjhtu9YB25ZnBPSM09QQY7q1CCIyOMD2bvN0r0x9AQzNfA1h0+/EOn947bp8v9LUv7+ZQCdpl7Lrs/KCb+jjjwTwMTWJRw6VLcQWQ7Afu6EX2y4dkuA8J63TTI1KN1eAPtN2uD4jXQiDOkMfkPGTQ6FXLI9NVJsxdBrtvItXIuPucliwmvRTX4E8vsoR/n34H5Cl2W3X8RH32M4PZw8WQcChoMGu3GsAbOroONhlPDVG3pPUU+lAMR/Z6PIovUbWV8lQEHg/O+REJbOSMWn2IExAQRqcGADW0pPmVxcpwtGaUa+4HJZqnJM1gyfxpNNI4FTbwGxfEFc+Opm565xZ5IOxWQH86cX0NNBR+vDouGLIL2H6V8NQDvQHs0fBUViltaOTxZavX4rqHSfdlPz1OLn4UXGn5slZ4Sae2/ZDe28kndA833oZFSz9Oc+rdt8GFJhxxuvrnwLK/F7zsGFWScrgdBMWDx5sJXzYXNRl7GH5oZoU5jFUK5LxCxu3KCloNzW27ADv+7j+xgC06LK7aQm5nWAyFPJ8FbZD55gGOFF/3yOKEIJlr8Eo/B+wUIEN/o/A==
  template:
    metadata:
      creationTimestamp: null
      name: monitoring-grafana
      namespace: monitoring
