---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: monitoring-grafana
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBhzEkyKb3fh3nAna/4xdliGEs1OS+Do7O/eYxCeZyfgeZrtASgx0sahN3wQPvfeu7cF5fMV5Iqj/2K5y/k1woOvjsWwu5nkxf9k1IB1r73BGeluqDvplBXb3j7mL9YQxkzzjcE8O+zFnQJaDt5oSOZY2xOgrBxTPbN/tKfkdIWRQUhv452gnIX+YJzX4xr8NIFi94e5LzZg0bt9Majf3CJFO1AtMPumLGYEsuEITTT7QzptLfzcEFzEdTbZIM0of3wmLcxlIvK5q/SL5J9ne0IOK9CvCvHDxCQdWof04DfjUDzsXzr8CqVzTJocub2xZnqQukD5B3uPsyTIcrb8023HOzY2br6K1j8rZVTr5Cwv4xt+yBjYP6o1KMTwrnSVTXDh0fvmfcsbMyR7nXKLB//6/Xq4dCJLHNxa2ZmJXvb5hBLtjvMJtQDlESa55q4oih6ivV8ROHqvaRkpmHczpp1I6Kd/0lqG61n7qLn5Sn3ugmlhH6jczqC3ibTcH+QXOxgVnxp62CKRd2R9vOkIuX+fIx3AZCVDsaoDcuEVMQY9b6nZN460/sfkJSVtE1wY5SETYeuf+GKG+XNKs5l4KqWBSqmbakhmWbw5p1Hmhjdesku0AXJks4v/ieAh+RxrFM6yh/LEmu1hLh/8dmd6aX2F4O+lDIua32bXstNN0TQwK30YS4mP9l9budbbCykCcbgZUgEoBizHHiK
    admin-user: AgATcbigUSH7CS+9hMell2AiwZ7iUisoUdiMxHiFWBZfNQLyHl7TG5Dm/9LJlH5sn/WD9w5OBNndodG0UbR7LcQ0iQV4eZQ+EufMA3c1kEL88/2meiiujF6MaoZy6RGbfD7C9fm1kX3ZsGsmAyyv4vXqHmQR5LnVfcgcRxKQJl3UYuzcFY2NqcX0IHrWPDJ8uslL7bpPRzHPBjJI/AAWV0BzTgF0pfpBTBDzFLJ6zxowow5HT5dmN5XQjldNCsYKjDSAIQUN4nn/41W+YfsqUcdLmYJ0EBHeV9XjNTtFGxCp/ES01ZDFMgShtMFWa7tGuuV7ht0DiuMpfXGLCNyOpByU37e2HJemM/MVoSMDCXVjC9ViNqSs+fj9js2xAkq54Kki/mNcugIhYzFjs16lQAdIAFFaFzaxbMG68A+JBlgdNENb25825AG68mQFdo/1k+SrpCmavKJEa4iC6nyGD63XypZh40N8qBED5E2pZgREV3IYmbxgR62QgL9CimrM2uvPipcu4Qo/tTxZ3NH5K3a32qYVS+ocxWwGhskWhTu2POJ+AUlOgK66fqbkXV46Xgsen47OLg+eJCHHhsCq+HKCzfAUYM0/KmIBo+sVAdb0uERSm+amJQIdjhbXnhqPNhlRtjGGxKT3svNa3g1ETyUfoDmjNMxAcMHLg6lS07uxj8qcCo3H057kH5n6pvLd1rntpJyiIg==
  template:
    metadata:
      creationTimestamp: null
      name: monitoring-grafana
      namespace: monitoring
