apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana-admin-sealedsecret.yaml
  - cluster-logs-dashboard-cm.yaml
  - kopic-ge-dashboard-cm.yaml
  - kopic-ws-dashboard-cm.yaml
