apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service.yaml
  - servicemonitor.yaml
  - statefulset.yaml
images:
  - name: ghcr.io/mohyeonman/kopic-ge-k3s
    newTag: sha-0a62ff6
