apiVersion: v1
kind: Service
metadata:
  name: kopic-dev-ge
  labels:
    app: kopic-dev-ge
spec:
  type: ClusterIP
  selector:
    app: kopic-dev-ge
  ports:
  - name: app
    port: 8080
    targetPort: 8080
