apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kopic-dev-ge
spec:
  serviceName: kopic-dev-ge-headless
  replicas: 1
  selector:
    matchLabels:
      app: kopic-dev-ge
  template:
    metadata:
      labels:
        app: kopic-dev-ge
    spec:
      containers:
      - name: kopic-dev-ge
        image: ghcr.io/mohyeonman/kopic-ge-k3s
        resources:
          requests:
            cpu: 300m
            memory: 1Gi
          limits:
            memory: 3Gi
        env:
        - name: SPRING_RABBITMQ_HOST
          value: rabbitmq.rabbitmq.svc.cluster.local
        - name: SPRING_RABBITMQ_PORT
          value: "5672"
        - name: SPRING_RABBITMQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: rabbitmq-auth
              key: rabbitmq-username
        - name: SPRING_RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-auth
              key: rabbitmq-password
        - name: KOPIC_NODE_ID
          value: ge-local
        - name: KOPIC_REDIS_HOST
          value: redis.redis.svc.cluster.local
        - name: KOPIC_REDIS_PORT
          value: "6379"
        - name: KOPIC_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-auth
              key: redis-password
        - name: KOPIC_REDIS_ENABLED
          value: "true"
        - name: KOPIC_REDIS_STATUS
          value: ACTIVE
        - name: KOPIC_REDIS_KEY_GE_PREFIX
          value: "kopic-dev.ge:"
        - name: KOPIC_REDIS_KEY_GE_LOAD
          value: "kopic-dev.ge:load"
        - name: KOPIC_REDIS_KEY_QUICK_AVAILABLE
          value: "kopic-dev.quick:available"
        - name: KOPIC_REDIS_KEY_ROOM_CODE_PREFIX
          value: "kopic-dev.roomcode:"
        - name: KOPIC_RABBIT_INBOUND_QUEUE_PREFIX
          value: kopic-dev.ge.event.
        - name: KOPIC_RABBIT_INBOUND_ROUTING_KEY_PREFIX
          value: kopic-dev.ge.route.
        - name: KOPIC_RABBIT_OUTBOUND_ROUTING_KEY_PREFIX
          value: kopic-dev.ws.route.
