---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rabbitmq-auth
  namespace: c2c
spec:
  encryptedData:
    rabbitmq-password: AgAWyoN6xfhFYeQWYuxzZUEf3Lv+KaAw7oehjhvEzzy6FLtwWR6Dd/cPOgXLCvepNZKOMO7ZV57v9hNu7kadcDKYNDEvtPNIF4dEcPFJgVrxsoG0ZvNrh8tDkXBeK6t9TWKGtNJ3DFnM7WCZig6CgexC+WrMHp4rBcc+d5IbgPOQluMWyfH3FaOLkdRijqyW+oyKiVm4CjcrCsgG6JouJwTvp5UTLmOHKhhEkK0t+ckzjXVQsAztFxxQzh2awr2TOq5NeIiZ2OGAay8Bl7aOgGVyUaqsCHAt9gukPN2K2cNAlHXWd72hajb5jNpvkm+OmyFuwJbGKEpOrqdm3RFJbktuWS4Z+2zVgQ4KHYACty0IjWwua2N/Ugn/GmEhvTfEZ6pJ3FDw8kL6p+3lDhU9DyFA23ZrKu23XAiubA6xXiDvEF/duATi26tILis2fPVTClgGK5VqZsTyFZKzB8+DQdi7S1Ow9W7X+6klUMY5SUUEdgqnTuwZ7Tt9YtALd0onEjJY5f5YeVYNwZjmk3TwykMa2vy5yiL3gJ2QojC5SsSQBwcHQUe4ZfDD/0e5MvG5aC0mc+FZL2jc7dXWK9SQiAIHe8EDgn3XWUwz/YTUbsvOb5NDRpGLTHpYyEIxJ3sfIX5P5kLplI62dUahDYnyXh9TN/09E5cYeS2BtRwcN6dTfnopy35nlMg/kEMpLwLbU0+51eZmnnvuumXt
    rabbitmq-username: AgCb9sdjh/VsETyQ/cMasJucttY+/jk+hz9prqoNivixWB8rv60I9mIDTd04UM29WWhWgBhGWHwC/jtkAeVd1/ZlMw5J2UcbSYgZT7MbLcA1zdbGuRX9j1VF+txMgGSSnLide6AsSwEXcUdxgAMWYkSRxaOXiUyyOBLD8NgudMQ9m5m+4Lu3+QZSWowTxjo2IgJHjFzMsSBRfS0ID2rKmBzJtV4Tl3WIc2ti29loI684/GchGf71ICla8C5DMl/L2U4GwaNcQoiJHt1aHNNvsa177/W3sCNbIp8mT/sI8qNbjpSgbKpOmJoRNjZS7fNMVYqushpfQggdP4p77HRb+h5VJIQpKJeFSoyHiOQw8pkIYTqbd3LrAOYdcgIWXR1gx06stvUyQcDXJsjdrw5sAMwb8UaO8ynMxJhzevzL5u1e6087ftaZn0A49mQZVbzTwNfr8Cs0De55HEVJVju9D70Qaxl2WZJn67UrrT0qckRJHu4qTN+etAeUtDOXGoS1ZJ7Fa8T1zps9kXCF2o5soP2X8TjGar1XTZIDGZ7CbxskTMPyAqF2iygi69vCud0ko85TsOIVDUpC6xpqsLxwHSz7AII8dOvPdRAEP0EpinHBTmAX48b2TbtfQq7DZo+4vDsBGtb9hdiqIviLOe54QnjqE1pm87WSuDlVQp4jlxJGd78/ezvlY2T1OVPRdiDXNVKWj2iFrQ==
  template:
    metadata:
      creationTimestamp: null
      name: rabbitmq-auth
      namespace: c2c
