---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-auth
  namespace: c2c
spec:
  encryptedData:
    redis-password: AgAAsIadbKUzpWePIkEKdiyVId64eAhribFN83oNtami+eDLbSdksOH/y58TTx2nNLtT1RYzoFwswKKZRLU9DhTS5iHHMcZK6jJWnACzu+f41MCzC7vpgxo0bzI55csinLqtA/S66rCXHDG4wVWUtMb1rmE7oK3CxlwzTPHQrYe/HuENoRuhquhWF7I7nMxfTbD0qrOFd+2EWld0ot8wSOd/h3Bkp4Ju7bE/kj2pPPbFkvaftRX+rhV6zJRnlUpywNG4RpcYd3hK9TuSVyCzh1y8dDWQ0G8qP7S3jnDauAKQFp0BEFVukSHVAY3J4Rj5GjsLA0AlRWG6mVsD0zmKsZ3dZw+IYQ01ZH1e6yAGe3RoqmX3GempSPxgtWsfC4XrN4skYn6tlzsdWBLei3kY34WM4HBkKZqn3QVUJPLrXVFHn+R0dNIrhfFhtoDzWZisopY/8j0uoMAeQ2DtZnEi+4bcw5Zfq1Biii9AHGiLoIbPuCgXerRqZ/RCB+it41NCrh+1t1LlBpkqngEcqRgdgwg5iGsankOFnG6DuHtOOKf8I8VYS2Ug8lhu18Dc9dzuQCUig31DDicfRietk9EPqBqeT7oYdiK7t9+ITX2Ze6qsii1KcswDQXz/0yYf1DYm3o8FdeT6ymV3MR5kGy2o3+YB/xjj+PqlpjFFfWRH6jSfFyK1Oye1LrdHFu7C5HvrfK8I2tkHzcS9ibDR
    redis-username: AgCcrHH0VTszt6HyVg0v268bPKHZK7e8CIVODJsVhnPVnVwFLsnB1CStZovrBaixo6N7ojxCaO1dyxRHasWmVctZ6x3cvSNHWnjTQjYhGCCnxUkytASUZzqLCHMVROXDIwat0w9H6qQExrmZHwIGbAZMR6M4SSNauiwsTLDORAQ6raA12oT4b7rmyI8E0scqPAvDMFvljFyJ6nYMjiBzPAHseAYo5fUuFLCafWDz7GF+IkfBfZSXzsmrGRnO6wYUCvaeH9vRSmx5qIwxdaV+K/X/X50d5BFskF5BvNxor7WYtKHEwYnShKIaQcfsKfvccQk41c42jybMiau3Wj4wBihzvIGF80T5+U4eH6DtUe/D/n5Aqu3k9WfPfwCRjOh64tU3+qq0cwvAQFbR99aC3eddZUDOwv7Z+ovzOOW9vLo1ojxo+Ywxb0BGzXS3SD/Ab9KuXbIdwciXNy2Aq+v3DcBPXFr/4an9bmgp1bMjwAceCypxYTT9QrsM6f+x9WcEcKPMEAPIpsDKlZlVdTR4/PnTXuu+oU6uMIR/A0KnlllYK8xwNUROCCecBNQbBhFjLTf3pl6LztBz4PZv+Oo1W3yxTrFV5fG+cKtvC8lhAbE+l13sCiLNbZCRnPDqez+ZEzz64T4XU2AtJhJVnOUiJ4SNSn67CqtuPHk7NR4af1IlKKj4pWxhs8PrM9txhZCTgQFl94WcDw==
  template:
    metadata:
      creationTimestamp: null
      name: redis-auth
      namespace: c2c
