---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rabbitmq-auth
  namespace: rabbitmq
spec:
  encryptedData:
    rabbitmq-password: AgC41C5XO5SS2pk2SgWunclbCzCbuOEuc1faWT5047zReICHj5kR9PT7/l/8y2xgDUWI5nlXQLZk9ofMa2bNc9Zn7MfkeIi+LqGKQrAkyYYchyZvb2dfG9LMYd3iN5tWpL0GcnmVUv1Swy5s1mi7c+1Rd6UU1QVyfW0HNo68Yb6Sjjk7JlZLz0R4NXhxp5MGQ+7s5TfK6SvlFbVuLGM8ut0ejrXcCr9JC7FTH7IZV2QQ+OP2yUxMfVAw9Wvye6BMe8SMPC8HiozTWLGBoBwFF5S3RPXPdBjxsBtwAI9FHjq2aQvipH+Qz3KN1a64FWFcg3o7zJUuUIrvRnLP9uGXEZ1VoutdO2EZq4VxO0pruaTO38sl3qomLOB9gz4XV9DLtbCrE/cI+XUdCXQaHuVLWZGRNOw9wqFDkejpDvg9ynRqiFq24J6GROMrkVmp/PUZ/QNpxSLMoe3v7ncJaeFp+USKrM4RVA03hcVJiIeqwNv57Bh6g49wDA+jwCemP3pbAPPZszTAzXcUkUCkASBx58oxTv2PsE02vIyEUplMqoIKzEFMQ9POAaMOict5cnWq7cxRNQ12UKgT98i8va91Bd+sZLaMjKrYnWVU3ozHt1MtdtEVhDngUI51EVMVUrBo/tvmxcED7KhltnfjK8k+KJ4d4zLclZvCNJPymTNYqJM7i1Ypi+PJzVzk/fhkAr6HrlnKe8SssdgKUONL
    rabbitmq-username: AgAlC9RGlTS+9bj7XRfluEGTReJb+MtBUxgJunQbH0kSyfhC+N0ZDSDpQtz0GU5ACC6uhu8LIwhydhZKcQ7hWYAvYbqcmBQClJVrJ6ciktykcLFL4wxOc4dxnDopa2oUfe5CtwmO/IQXQVm8Ejpo70w5lMDsSLEnsGv0s0nFPZ+ByTEzUCpDcoTba5wsT9KX6kM7PZ3K4R2Yv7Wv+jQL6Ighb1f73bagAFCxWcyPo6Wi+HHsH1V3tO6La2ZDo5BHz/J2tAp1A0U1b497mQ7Tb5DOJ7/GLSpajAN7JK1sqbJICufde6hE00MVzrMSgrMOghVbiRo6q1YVi9p9esrMJAkuT+/fweIhSh9rs66nZ8OTbY0xbpYG/J1F3iU6wK7xg5nNulq/CnrKjNx+Syks9ttZgNBcgkUKSFMvCgqziXKSs3oK9Xr8mnXU9lIhCO9Tw9WZFMeOqw1lo8PdO+C8qjBNheSajqJOdYO/UO8bQJgS/AJ0idrucsUBpE0NYqilNN5B296uLijBoY6QZiEsMJ02hB95VIWKlpGbBrD0LDwRDSC0irqMW/qKJ14Pl4gaYF28EzY5vlbDUGEh8Tnh2oN5lOMgribWb0mmCez+lSXuJ87DFr9xNDoao26u8pz1eDMtmCC85R3WGMGag+DST4KWwOyIzR/Wg/gQwJ0TIYGrorJlgTSHmJDRGcVIWjom4H7Rdo4Xkw==
  template:
    metadata:
      creationTimestamp: null
      name: rabbitmq-auth
      namespace: rabbitmq
