---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rabbitmq-auth
  namespace: rabbitmq
spec:
  encryptedData:
    rabbitmq-password: AgCXqzl/ga0qIWq8AmtU1d0mJk3sDvhflgB/FucRPu+SGjTBGiWnHeSXn83J1wrzHTKJPueVIo7z3Jo7Wrfb2AxrxMvVk8wKbb/4y/wylQzXiQzXp0/XyIQDOFdksQAqBAoKhvbYTopqEtlwr4zBcZKy1kf8c6VVgJvbXnRSc8asKtH0Le9kuqC+TKXMy+OIV65gGTxXBfDOaKdGdVvv+wuhQitXHiZ9aTpUaniPTn+Gk4tRN4/2lmsG9zldx0ZdqxXjTq4QTauosOfAsW4caHDEmzK+FHCL34qsJUzivUfc1VjiZf5fiBHoJXcFn7zy4C5vCQWADv/wLZzlLglCYRXOrB0w+TR4BZlJH+9wwPKIRITFERRg6KBLRGLYfsdrg9YadNhIDmi2M7pF87DHizL8zh7Oq2riR8iu0aMFitFrLzcCfD+yfzWRcZtNdnR84k838ThE5wsjN5fEWC2V3g/0HFWT+EMf26fSm6uEqOPlT/HL1geGimlLH5jJX/QU6pIGv6V/y0Wi+y44p+fLp2uqaXH7JnuYrsvRbYLDqSdSRGjtQ7hikTBjaY0sG1LH9ocjKFbIH0STGAPckJ3x/J+QWZnT6y4BuFc/QtZRb1chqx8HqPqhw8fDeMwQ1bROa9GhqJdgF/kzmBcPRtwtznCBg7+uvZCZlvb4zclZ5oGnAIYjPkzhf8+F4eO/9XlvrLjdDV0m1/HYBUzkvDg10F8wUs3B8VzPA2gyClKZDu/GUA==
    rabbitmq-username: AgBbRdN6i9nhkFk+0SDfBaIJiigv2GIkfCc0tl6fI9nJ5ZCzYE3l8tJgaRiY3ihmpd04V5RY+7zJTMBPO4a+qu7OPzO+7kXFb3HoWFyRLxnvZsLIQxTp8U8d+gfFYe7gIXaquZs9N83iNkCYcGE1BxbXgZuCXOv0GwKndioWJYuCShagrMsWRLVSVC0J87/yh0za1MN5BOZiwHOfMnBUi5k4/Wc+jCWLZuYWNzUCbQ0O3BxySx7cu8feAHhjGk1lTletiDfxrWmRWoPIv61yi6rvxlu2Jy5LeD/LkhrDOyGfWaorD3gf9NDptibeAnJkPLWFHO6MToi9sNRG9rtwtRrY+J+OZ5pzuz+LFwUyEyJkgN0ljh8iV1fPnwZVT+6eY3ZRKdlzsvya+ueJNtlg8UoEjj08nZnQ+MenJ9yOliifleOTDt3TMJmi0whwbqsPVVzWa4Yg7t5F9foQp999p9DOxnBguO46fMG8OWSUw7yVTrJOjHpvWcKGdRO/Hk8nFA/2KMSzJRrzIO4XnYBzRmKXHbl/Zh/dswQnMVtyyfNajGXE6lIVNIiBIIhfxlnvQngNXPsXRw0fGMAWPbyVFa0GGC8qRYRFexzYOKjcFAjh/T/lvxu3MsV9PkQLbBNl+AlZ68hzC0ywH/TxBNn4/ZQzkY9uFIHvka7YLMozgWGYUOaw21kdfOxTtcLvaOiB0qKQWcAp3w0RfeRAmjXp5w==
  template:
    metadata:
      creationTimestamp: null
      name: rabbitmq-auth
      namespace: rabbitmq
