---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-cloudflare-dns
  namespace: kube-system
spec:
  encryptedData:
    api-token: AgAurB506AIfqO+/6NUdS9MiCOAbNd4oTDacgXidl67U3IZqekf8WKPBsQRuPpp1bj4MY5ElHbc/GK0DTyM6y+DwOGdiLFJ2cn5E8KapGPh7xmVDoQTkbkPPqpjFA2D6aZZzLKht2lzidpV3FQSlnJZlZhbOp232XyuroJuH+0u6AuKIgI4971hCAWN9CPU1iKsD72WjZhskYs9A1quwyHJWX0ZfYp79Q8IKevBRKFFvKn2ThxhbXZ1Ywgy0GjG8DOdkIXtim4N7egQdOaxn86JebedlofUnnXA44D7q/NMl69RyWWMh9vJcz6V+qzDna44J/mc3mdBwM/WuAmROm8uN2BSsC/+DwGgi4VLm+mv2cZYZ5llnUOCidzPZA+Eqhiyfaz7KS26WSMbCRddWA8Q6vf/zXdm/bBc14QRNWRXi4Sf15F9b+5uYHRcXVqXMU5yhOjZZMqc6liWhj+GwWDz1dae84UtCk17X7jc61aKU7/L+6b28JlGffJKcGF4CL73som1jIw7+K3QpUiOzOCVhNPXXVNKvZ9rQAw79F5+4sFwxWg1TerpteyCZj8NXehhJPMN0pYdg329/lrJpVp66yKWMU0emqhxznlzBBq98jIVIuR5+W7DYLVB/MFa5PB4EYWx2rOOx786gvolcq69OjqULvTUJAiM9+5iLelmSdHRxJGrJg7xNWPD3bRnis4qCmeE0ZV5cNIdDF+7U+wdADd969o1mslroQUAh52pkE4HBlV5SGswG88dD0XLcT89x9p9Tjw==
  template:
    metadata:
      creationTimestamp: null
      name: traefik-cloudflare-dns
      namespace: kube-system
