---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-cloudflare-dns
  namespace: kube-system
spec:
  encryptedData:
    api-token: AgCURqVAXdzWwE6kTVf0UEbouHg8WCmbdeKsyvb9YTSUf5dKEI//MZp7jbC32bt+wPm4pRmmtHvKEZ50+O1j+GIVKz9jOF78MLuGTkfrSA/3k2RbFAk9V2yzfFnNPN7zMWfPaiP++hdwmNLKJmZCD0WkUBDvRexDuolhE9sjF6LFycST2d9ROxt/9LrMIhvDD+UAdTyjFHRSI/eMdo3ByaJNnyfOmBultZGMBv1Wa16y+d1qY9Tl7qntxAya9fiMiE+UkXnCpOJSYLC0TMg/Sg0DJpniOeh0cmbqiAGOyll295aAE4TdEtoguul66vBL6w81kr47a3eO6xXQ34DsQvtpTyzOSS+pHYQL4aBPNR/jECGWY3wzY6n92wAQa0wUPoLMbRbDQ9fEucc+qfgLGowalDO/7VpiXYbl1dM7HEb7EIPxb5sg5hWool3O7H7ktBCXGrYuN4SeJvOVMrjaibfs3RJibbRJk5nGdMj8tK3Qyh8gUcEgiq/CJmyLaFSr0SZlyAQgY/IjTVztaoepWUo8h13s3Ikps9NRBgBzshUJT4sWQTX3U/9y8LunOIyfaFmC2nHsn2hTgA9Sk8IAgufLwvUZFTnarWhZQAHK+ooibZlggnI5f8Q7EU8ImDn3AJYUPbcvyQL76hXSZvV54y/k5K4rTWJfplo1HBl6mDXS2MTk3hwnI1XsHG4P3Q+8EbPAzQOBw1f8TDSoGMc6gQZUq3ql3MnG4cQ35EcuxMap+SMYR/ELHnDXUjNDUAzZNH7ep1eu6g==
  template:
    metadata:
      creationTimestamp: null
      name: traefik-cloudflare-dns
      namespace: kube-system
