apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ports:
      web:
        port: 80
        expose:
          default: true
        # redirections:
        #   entryPoint:
        #     to: websecure
        #     scheme: https

      websecure:
        port: 443
        expose:
          default: true
        tls:
          enabled: true

      argo:
        port: 8081
        expose:
          default: true
        exposedPort: 8081
        protocol: TCP
      grafana:
        port: 3000
        expose:
          default: true
        exposedPort: 3000
        protocol: TCP
      redisinsight:
        port: 5540
        expose:
          default: true
        exposedPort: 5540
        protocol: TCP
      rabbitmq:
        port: 15672
        expose:
          default: true
        exposedPort: 15672
        protocol: TCP

    additionalArguments:
      - "--entrypoints.argo.address=:8081"
      - "--entrypoints.grafana.address=:3000"
      - "--entrypoints.redisinsight.address=:5540"
      - "--entrypoints.rabbitmq.address=:15672"

      - "--certificatesresolvers.letsencrypt.acme.email=본인메일@example.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
    persistence:
      enabled: true
      name: data
      storageClass: local-path
      accessMode: ReadWriteOnce
      size: 128Mi
      path: /data