apiVersion: v1
kind: Secret
metadata:
  name: postgres-auth
  namespace: postgres
type: Opaque
stringData:
  postgres-password: change-me-postgres
  srrrg-dev-db-username: srrrg-dev
  srrrg-dev-db-password: change-me-srrrg-dev
  srrrg-prod-db-username: srrrg-prod
  srrrg-prod-db-password: change-me-srrrg-prod
