---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rabbitmq-auth
  namespace: kopic
spec:
  encryptedData:
    rabbitmq-password: AgCviv262DdkQX8YcH+WNujR4FEanahYiM5tGfYVJjqpHqYYna/0Fdx9Mu81cqL/6PbWLb7rrz9LmFS751rbcQdOwSLK5lNdnINSHdl28JSKvlNOcfoh6B4n/vGui7ubp+WVAlDAMPHmWvlVMWkZfJym5GRf8TXCifRIGWiU0ovNRDKHRAzIERJQR+UX5kAh4FjBTK1cEBrHErloLy87/myrjhrMwbECLThvgRFTF50gQPJotmcKN+DeDjH4CUVY9Ytvk9ho5s0GJ9LPfZMlchxK+L/j9RqthGpNwcXQmj+AjP9mp33+usN+ofgY34ZjtbTEdA7FvOTGPIuEBSsXhyzUWsHdgsChd5nQlXARcdNDuuOEhzuTYXY1XjxRZ39YM9RT95G+UT8nIADVlOcvNABdATxjA0m5jqreTWChD+AnKhuWuTDJomy0+v1YNY8qOeOd64SEaIIdCDhmWWluF5q6hZ6R6BjSHy+7ILWdcsoOzWKvkJWs5D9PeWr0otgfiA7LIM7k46DhSrtZ+nOAdBWgWbGK7CdsG44KKCNFjyQf2BjBTz3tiRK0lPAUtmDE1yS4pQB3Wo+4fmiveXg2uhang6bsW9FVER08e2qp95UqV+zYYCe6FdvQW+5H9FZcijX+m/CUqCK4qZ7cw1zq3s6NDPbnpFvrUeX0yph3/es4SEmbqFTHQitWmn61QePCMqVYDKfq08h9dWPV
    rabbitmq-username: AgCEsBRUrJpBZfZx3GODsRjYTmKFfORJNxjXindUMNwM78JfQ1+Gg+kkIbI8I3f3yuFz5Lg02WM/bkxqoJrTirBUk2Jn2QiXgZ7+vE+jiFLuSfu+c3KSzlA3O5IvWQUdq06zqwwgQNxBSys0bAo5mNSD1wz26TGW0sk+9ZR7EpHMxymTOdEgCH41wUzPtQMdaza+PRE8SGEGyOrLqnkYlnyZeVTMdxJgr789SEmrbAZwRHB/6ArlQMsnHm2QTDcLAzJUoO2tY1LKXPzXKj4/7vJVX6e38JdqDsss/e4oZkoBB+GC+0H1qFWrUhWagkWCwAFJgfszXadmU8cmZI4MmuDzV+Fg/WaYQDP0EQlSAL6eVtyw2sFyAkWrA3fyScPpqiITkdKwVZMI9Iw41E6FTKrry+yhGSiB+kVFiSqUtYvvK7O5r80nba2ehBC8mcyEm5rU4IKAPjSsdLOn7O6h/6Sj2jg04yk4RZIni06CdlJVb67mjT1mpNFDgfBj+rTlKINBTqwO4pPMBs6PQTXCgyoibKfWhbaB17H4PiRQ89mlgCPoM2MaIYEGiezKsaldgz+dQXhBFbLzT7KSlTyNtFIsitX0h7JvusEnq9VZKSXLrxe5swPSGkoANneyKfSi2BVd7gPlS3QkH60cOU21JvHrS6P/77V7beLnf25dfZYjnZvYh6iMYZiVvdl0V1mR8M4fAUe9sQ==
  template:
    metadata:
      creationTimestamp: null
      name: rabbitmq-auth
      namespace: kopic
