---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-auth
  namespace: kopic
spec:
  encryptedData:
    redis-password: AgCqil8KjaSMVIVyfYwvdB5E56MoJl0Pkh3Z4xgDNtmH1n52saEVE7RiwmSf4bLn4mtnvmk/1a2D5QAFLgmDRCot+Jgi2iJqkVQB162/MLjsfogh897eRKhvtTpo2bQXgDiPyvRORk7I32APFeos1c/ZipuO9npM/zxkT83jtvfuRUW7aUCyVkFTJSoqp15gMA2T0YQq2p0bHC28ZjuUGlzyijfcEKRDO3VrcqWV+8cKKP24232qi68sxLMiCMvaIP4dbAr3SwSNqralC100bf0dVLvxRwDziXubIPZtpKsdL6/SZXfwavyTJfD5U75P1t4ainNEHvkLFlsAFzwoDSXtLfQrdpBzthBF4dcZ48ETbHJcpcsyzKCbTTpE0S7Wdv7XtaYIZAUMlqJkeEUVeGxeQEwWQXF+RMhn70gyhscT3P6JW3Pr+E5RFYqIWKC3jrp5QOBz2S5/0tVoji4VmgEaKTTq3h9xNvG8InqZmksjOoYKh2ukxjnGnBUL3vb9bBjIL2e+lKZoenysgS+Vfc7vgjopJKN1awvG6Obi1E6TZ9U8xoEqI9uTp342XEtjOjhq0ZT41FolmVAZg15UTWooxJLvTW18Xmioy2IyiTZ7/gS7TDN+d6pcku+Oh8V+bPcHMavbEIzm8GYOWs7wPiYhK0oRlQBhvKGCtVkW+R1pjByFN6K/gaKfZmZS0ObkOwc2bIFc/0e/4q+f
  template:
    metadata:
      creationTimestamp: null
      name: redis-auth
      namespace: kopic
    type: Opaque
