---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: route-token
  namespace: kopic
spec:
  encryptedData:
    secret: AgAQF6UwYGHVXqY3mK67f9pseAlhJAlwdDyRPV/k3jPlMEvZYd6uq8V7pVFDD4gekJP65k+29ENuHEjQTJnNWsJtgU2cp4acN3qQxKiudxvAn9+pobFVHtALtzTc1tZnp/lTerCy6PWKjcYE3JCUudpTMI6XmQfNqB9lrC/7iQ3zhiAPTG/7NcN/2QiW8rN73VTZRzAIou70O+NgtNGH5idKxTKGd4XW3LjajqMVXtMB0lhOEZol+FZoE+G36PU73PQ7A0b9KqXukelO8Zi3mSdFa0Uil5jyK9UenISwaBg7s2cmoKEdPBQgfXhDeDSxNKxmL2MKBV9Yr+cNt3TcyUzTsCXJnmfFXuIWVkxeYHUSr5N5dycRinqtEcL/hTsZvGG/InMVYBqyXOLxleds2BIYGRgcvDUTnH9VBH69+9G6MA3qRiNL+AG91tGh1TljjR8NMDnn+DCz0pIW8xKDbcJhm6skf6k6WPA+sdvAkbY2CIgKUrjOfhV8woF9s15tpDEcFbfskP/NPTPjCKT1zGxy689+g+bC/rlVNC25ooBVr4rW/Ay/8ZV9i17gCXeM4k5/G1DiM5f8M/GXtV+1k6xIU40/qAihoRmcW1qFH4/NaQHXeOmv7Z0Pzxxx4FpRe/sRHZoFHW07VeLc0s68ushBRgkzJW7HjT8NpiD6gm/l1QkdTgHtWgKdNB/5iHhzJ8/bT93Bjp27jNXNVo9RmKAySEL+RdNCqk2eHUbEmBG97/VZ
  template:
    metadata:
      creationTimestamp: null
      name: route-token
      namespace: kopic
    type: Opaque
