apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: srrrg-dev-app-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.priority: "100"
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: cloudflare
    traefik.ingress.kubernetes.io/router.tls.domains.0.main: dev.srrrg.link
    traefik.ingress.kubernetes.io/router.tls.domains.0.sans: "*.dev.srrrg.link"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - dev.srrrg.link
        - "*.dev.srrrg.link"
  rules:
    - host: dev.srrrg.link
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: srrrg-dev-app
                port:
                  number: 80
    - host: "*.dev.srrrg.link"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: srrrg-dev-app
                port:
                  number: 80
