apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 81.2.0
    helm:
      values: |-
        grafana:
          enabled: true
          admin:
            existingSecret: monitoring-grafana
            userKey: admin-user
            passwordKey: admin-password
        alertmanager:
          enabled: true
  - repoURL: https://github.com/mohyeonMan/home-k3s-infra.git
    targetRevision: main
    path: apps/monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
