apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mohyeonMan/home-k3s-infra.git
    targetRevision: HEAD
    path: apps/web-demo
  destination:
    server: https://kubernetes.default.svc
    namespace: web
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
