apiVersion: v1
kind: Secret
metadata:
  name: srrrg-db-auth
  namespace: srrrg
type: Opaque
stringData:
  dev-db-url: jdbc:postgresql://postgres.postgres.svc.cluster.local:5432/srrrg-dev
  dev-db-username: srrrg-dev
  dev-db-password: change-me-srrrg-dev
  prod-db-url: jdbc:postgresql://postgres.postgres.svc.cluster.local:5432/srrrg-prod
  prod-db-username: srrrg-prod
  prod-db-password: change-me-srrrg-prod
