---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: srrrg-dev-mail
  namespace: srrrg
spec:
  encryptedData:
    SPRING_MAIL_PASSWORD: AgCDblMXI/5fxQyC9lvO6e9g0lsD8l3yAmJD2lTvYGctRJkl+0y+00bK+Fd+Tkvi3N408GwTY8PgApr/nQgxz0uxtqNKYPbEPwl+29LPkVwxu3Md7tZTfPxcL3Le87kxfF3LlYcdfHPN+CP0mJ8bLEsUtP9Lq1AltG6NPC728GjjVmsOi5zm4kauuTQbA+jdRR9AAE0CesDtx0MxaS1jFn2LaAG2hyt1Y0/lTiinMqd7qeq+KU3nBlVlAfgJ3EMR2YgLbRf4ufZIofLoqGTfqoMcIt2bnzsND1qERR/p2LeTzzP+YbsLaxpkct0DiC+8XQ6BX7ombeZ8iyqYOvAzYyt4HPoRBioytG4FoNIdKXR9syT0Zl2HLCciH8CjHlEnje/QHDj/afh2TAg2LOglYpGdHbYmHccqzJmqVesDnYdjJo+DtkqQxKEek34B1ki+0Uqy1cIIxY6nVCw+oXokI45EdDuQYU6UHdOU13aN884dMOIk0TnbHCkkCfSPCJvmBklX7Y2t6uUrSaw2lfb0UWDkg+W1BnRHoQVH+6rn4/spTMRKHATd8rux2Y31aMbK7hf8WcFL9ogXp+XylzR5rTa6hpBThjR5l3NYVX/X1Q1eUyb3fPcR2oJ4I0+mtOCbPNqZRDUCiRQE6684aXhYVJ5gsq9nx4eMQzVSNgYpOYKz3elEnuA+TAG8wzm3efoc68bwTs5dnAz5NgrAWmXsOSf+
  template:
    metadata:
      creationTimestamp: null
      name: srrrg-dev-mail
      namespace: srrrg
