---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: srrrg-dev-mail
  namespace: srrrg
spec:
  encryptedData:
    SPRING_MAIL_PASSWORD: AgAIsiSW+6Wh+IKgMcavjkv+V1Mc5/F6VW194FV1y45ubPNrm+F9qmpLPH/Vr+7KzYsOlUYZWJ47Vn4Mr+LVul7HQkhCCr4tZoYST5ZIkUvGN3RqxntLV2bAs4YL/sih8aV6idtwD7G2y1H8VDIVtov27cQqEYrbOPhwOmBjOxUIlyfBkxfbwDMoDoeVlrink87f7FJxLGzxWaw66dU0azXT7TFQ55rFP28sZ5UDnzBPrZRRIE77alsWC8ZxcAm90BHuRAYiHucqZxjlQxx3k6dHe519V9hAGqZRFdyx+Wk/0q+KPKF2WXmGa5iDgaaEg8jcCyHeD7fg+Mw6dC6J5o4JyYGm6kJ5WPQx/wQMrtE7dptUJqZ4CRfzQl/7e2k1Jz40cHlIsB9dc6ktwhhcNQAeVgctmA0YOl0C4CiBOd1IL+DjfHrq9NdRsy2T3uXnHMQrmlU+m+/35HzvRp3vgWrtHkYiyK9HmMrRxY3FRXWajR96wxky5ks7+WX9BQDh2M7MnzsN5GzQNZFo817dpus1fh3R80PBbUtMK4s4ezBDQG8tTWtDQopuiXa7saqMwLpFUhdkUK1q4XepjKfaEDO4shny/kUVUUevwzF/INOQKRaB8hhxypPfkt1wtW+jkBZkI+ykCGclLO4/I3+D05XIp0jOorrgUzcwRScoyvIfYiWUkrPT6CJyeAoBJdtoRq4LxSNl11Q79AdX2WUJSTRmhv1P
  template:
    metadata:
      creationTimestamp: null
      name: srrrg-dev-mail
      namespace: srrrg
