---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: srrrg-google-safe-browsing
  namespace: srrrg
spec:
  encryptedData:
    GOOGLE_SAFE_BROWSING_API_KEY: AgCDVlBfqNMxDlcApDh8SBfv17AzcBLUGd26/X8C/O6Qy7uRAxxDRBRqyDq9N1nWVWRO2oCWGMEPHo4bV2pr5B049THVbXMB1FADN1s91ZnKXDYJufHNHLH7PqVvLrNczuijtqzdlV/ibUgn6uKlNKQgeyPGQD84SZGE7/9RNkteCpzR6HsWxC4rGBe4fbT7mLFovme6LQqIZEEYvOMnIgkC41RTiofbxeeNmaUYddhH98KkkoNMcElMMcwuPiLEv8jwQ8dGxlgawoQ7Q1qtTQr0kJEZuVPyNH/bfBRrD26VXtWQ+76jAyVnFMU+csu/qkfqx5CsatDIAqe89qu0h6uC1gWMbWPlVuYI60K6pFPQ3zIDNfEHOO2/Upn4IGJLwrG77hemadSkAqO35h6qntyEEV/cjXiMuBdPkNczfAdQLsrdHiG7r1myMg5PbrciwvMXcPOCv6vlvAAdJSuyAfYSM1C9r5HT3BnBfTtM4bH6rQ223sFbMADMNVnoUl230Ob6cbLeHEtWb44YVEYUoynz7ml2Y5yoKyWWCtgi6sGH2LMUv4XYjiQ/XonsxfbSHQCE39G72nHeQXs8CkXsn9DjvP9Nch7TeRuSqMsVebj7aA8Z7H6L/h9SSl9CEoGo3qnj+q4nSvt1nrXMcwQ8PRaorE3QJWWe6BtSSr8GF7YOYwANJCKW62/WU0xcywIHzlgbkZFeJJUFscRVp73uT/o9KB603FtkWjOLdFvTyFni9k/9rgyyXlQ=
  template:
    metadata:
      creationTimestamp: null
      name: srrrg-google-safe-browsing
      namespace: srrrg
