apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - db-auth-secret.yaml
  - google-safe-browsing-secret.yaml
  - application-dev.yaml
  - application-prod.yaml
