---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: srrrg-prod-mail
  namespace: srrrg
spec:
  encryptedData:
    SPRING_MAIL_PASSWORD: AgBhz2c3IxDFjJcIGfTcPC4XeFzk0G8TY8pQnJWC9ocTVHBpUHUiXcXjJQFiG3BBOMdJctudYO26ZsYsR2M2HaAmEbwm47qAzgh/SWYlhoj3xbpRTUlv3GEbLkmtp1uXMgk/vSe6/jZoOc074YuSGVFEuQgkyGhGdRO2XTbGuZuEBo3zZqzUV9D7miTrj8Miy01Z5X4YukaHSxRI/kMChkfOWVIJCEgVvBOSTxCNtxvPGWbB129D425YfLytpGmGjvpwD4idkHA/mzUzHS0zjsKatToGL2GRuqzYAwf9T1Gh4aB4dxRRDTa4r8fCx5nFSQlLu6PQ8UufL42GEiHNiuXqWHVabSwYtU03HqizPU0AHxzn0rJOm3rO0qhTNoF4QNwFuV6R2LHhMLTb+8ITl2KGlk2j3Kg+fVlXgi8ThI3CvY3mr/IisFTsBIvn2QHkHxHPrMdxjuBXVPO+eHpoQTeeYtmZG5Mm/XIFTiniYMNPmAIqXEolxzh1453qBmpDecpbIqZwubzaHMBBPZVFmmnUVjmj7ZBlCm1zaVqfoSAXTmkHgtC40SKAahzdV3Xk/mQdqzR4tKFWDgLMENnTi+v93VqKLAkWBZbNTTvB0gNmb3ixUwUZ1p49q6B6Nap9eN3MULNp7lG10fXiVKkW7Jktfkcl8fFZ4RjK1dKVqOHjiHxrKA+RRw4Kiht5PfU7baG5Yx28tOa+ZCsdyRI696HR
  template:
    metadata:
      creationTimestamp: null
      name: srrrg-prod-mail
      namespace: srrrg
