---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: srrrg-prod-mail
  namespace: srrrg
spec:
  encryptedData:
    SPRING_MAIL_PASSWORD: AgAxb/jf0BC/8uRNrV9DUpbYKHXUitwh+ChaIYAVvZ72+lBp1QR6BIlJe4FbNNUC+FrEX5iMa3RdJqsurv+xV4qMiHNrMRFBlyWYy197Aj6uFsEzExCYbhIFelrs5XpoP8jvKtP48LsFkJr/jxk77L4vAx2fsacuyjSwq8tZqWhZJz9+6ZvNzN+61VtBK9DUcoTgQminnYzXBjTKS9LqGHunUkcGxTnb4tAvD+xz9TJ1Y13Yx3qpnEF47e8WYMzl2oQmvnrhdhrc4Mu4rGDaXvzNWPFwxy/4MqjfZqsHWFEh/WnmQKLaWrBFmILUGEKQh0hvkjtQQ6uMisNcTH9GdNqIHxHO8E4f4U8Gm7bLwHcIrVuF4IWlqXmOwZ6Khpla+FZtPvjiiBYRNzFtypgWTq0d58nEGpUlJLlWayt1C75uSF2wUs5e4pbnyAWFE7b0N+kaLgH+PzD5QCivjKeE22vowbgawvJ2mVqWC3xeAb2O0MsjmVprl879huvRr1XCTB2dkAeEW4vqiyN/ASrowpc7z/OMi/f0GWMgDLDpRiV5skD6rcyAKv3QMQmBccUPN3ywy+SKgFg21GthSHwvXfQIOoWh+5JhDwTvs71tKKZwZZoN3o5zP50MM7K3qPfN0arnMTaNlu2+AKAGOZezeeb5POmgZu39czh85hcMmUHHhGS86mqp+5dJjLfyRRYhNdhZ8eHQnpvMYLs7q6NiokjsdqV4
  template:
    metadata:
      creationTimestamp: null
      name: srrrg-prod-mail
      namespace: srrrg
