apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sealed-secrets/application.yaml
  - traefik/application.yaml
  - monitoring/application.yaml
  - rabbitmq/application.yaml
