apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: rabbitmq
    targetRevision: 16.0.14
    helm:
      parameters:
      - name: auth.username
        value: admin
      - name: auth.existingPasswordSecret
        value: rabbitmq-auth
      - name: auth.existingPasswordSecretKey
        value: rabbitmq-password
      - name: persistence.enabled
        value: "true"
      - name: persistence.storageClass
        value: local-path
      - name: persistence.size
        value: 5Gi
      - name: service.type
        value: ClusterIP
      - name: image.registry
        value: docker.io
      - name: image.repository
        value: bitnamicharts/rabbitmq
      - name: image.tag
        value: 11.16.2
  destination:
    server: https://kubernetes.default.svc
    namespace: c2c
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
