apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  # Add redis-sealedsecret.yaml after sealing redis-auth locally.
  - redis-service.yaml
  - redis-statefulset.yaml
