---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-auth
  namespace: redis
spec:
  encryptedData:
    redis-password: AgB9dGyfHKy4w0QN3marQ7eLxF1ROnuERSAVlCvvA01zkptn/mDZ/I3qnYHxkLM1z71WMWgPn88r/He8yCF3nh+T+l6rOWdo8Csuqs1nl5ekAxc+nFYyrVe2UBsNb9h4K/iAUg/w3v/kqykrjrKdId2aIlVIfLyYIJjvDpEt0PlZ8qzzVo2E6HfagtnmcMSF2hSCkvLxeeemTWY6oC56dNGFdaBkXtdfzLBEwyoCi7/YNdIq6HjKqFosxsArxEhjL6v7n0L5ceCXYUgNihdP1EG5VHJv1Q7hqlEbi+PO2In/HjKyS1IQbJfum3aLvRPsNDCe+DQHhVULfEwCUddF7Qk2hQGzVpAp3+dj15F6Plg8QZNvsEYBzkJe09YUziIh8McvFKnpxdO6tQgB9zEnjGtH2K2Gd/+uyJAcNnJrPFPRFr5cXRaubX4gTW8iLU96YnqLZpgUWjdqN9mc2gheSqJB6m5RQlxtDM6p8bXPAav5YGZTIe2+HUkqJ9oBdgM2qUbKmKU7uejF+ccknFiPpVWDlzwkXSbj5i6xB/OpoSyBYgPGVP+clFER00FeleXAn8UyVrELgGpZeE0XbMFw1JzitnwcMuuBEZr/4+pnIei49T3l++aIxFj4iLjbNpmnHyK/pF8+xTVccgSDq8WKAyict0PGYEaYa2CnZEiafbL6pOJHi1MS0w9GuB0cfGLZ4aJzR5Jq55aALnE9
  template:
    metadata:
      creationTimestamp: null
      name: redis-auth
      namespace: redis
