apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kopic-ws
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: kopic-ws
  namespaceSelector:
    matchNames:
      - kopic
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 30s
